/**
 * Mapas columna ERP → columna de la app, para las 9 tablas que la app lee.
 *
 * GENERADO a partir de `peribus-incidents-admin/scripts/sync-incremental.mjs`
 * (8 tablas) y `scripts/sync-adm-tables.mjs` (conceptos) el 2026-10-08.
 * Son la fuente de verdad: definen qué columnas se leen del ERP, qué entra al
 * `raw`/hash de staging y con qué nombre se publica en `comercial_adm_*`.
 *
 * Si AdminPAQ agrega una columna que la app necesite, se agrega aquí y en el
 * schema Drizzle de la app; nada más.
 *
 * Ajuste manual tras generar: CTEXTOEXTRA1-3 en documentos y movimientos
 * (ver comentarios en cada mapa).
 */

/** admDocumentos → comercial_adm_documents (36 columnas) */
export const DOCUMENTOS_COLUMNS = {
  CIDDOCUMENTO: 'document_id',
  CIDCONCEPTODOCUMENTO: 'document_concept_id',
  CSERIEDOCUMENTO: 'document_series',
  CFOLIO: 'folio',
  CFECHA: 'date',
  CIDCLIENTEPROVEEDOR: 'client_supplier_id',
  CRAZONSOCIAL: 'business_name',
  CRFC: 'rfc',
  CIDAGENTE: 'agent_id',
  CFECHAVENCIMIENTO: 'due_date',
  CIDMONEDA: 'currency_id',
  CTIPOCAMBIO: 'exchange_rate',
  CREFERENCIA: 'reference',
  COBSERVACIONES: 'observations',
  CNATURALEZA: 'nature',
  CAFECTADO: 'affected',
  CCANCELADO: 'cancelled',
  CDEVUELTO: 'returned',
  CNETO: 'net_amount',
  CIMPUESTO1: 'tax_one',
  CIMPUESTO2: 'tax_two',
  CIMPUESTO3: 'tax_three',
  CRETENCION1: 'retention_one',
  CRETENCION2: 'retention_two',
  CDESCUENTOMOV: 'movement_discount',
  CDESCUENTODOC1: 'document_discount_one',
  CDESCUENTODOC2: 'document_discount_two',
  CTOTAL: 'total',
  CPENDIENTE: 'pending',
  CTOTALUNIDADES: 'total_units',
  CGUIDDOCUMENTO: 'document_guid',
  CUSUARIO: 'username',
  CIDPROYECTO: 'project_id',
  CMETODOPAG: 'payment_method',
  CCONDIPAGO: 'payment_conditions',
  // Campos libres. NO estaban en el mapa del Action (por eso existía
  // sync-update-extra-fields.mjs aparte). Aquí son obligatorios: son el
  // puente con el negocio (unidad y folio) y los usan las reglas R1/R3.
  CTEXTOEXTRA1: 'extra_text_one',
  CTEXTOEXTRA2: 'extra_text_two',
  CTEXTOEXTRA3: 'extra_text_three',
  CTIMESTAMP: 'sql_timestamp',
} as const;

/** admMovimientos → comercial_adm_movements (26 columnas) */
export const MOVIMIENTOS_COLUMNS = {
  CIDMOVIMIENTO: 'movement_id',
  CIDDOCUMENTO: 'document_id',
  CNUMEROMOVIMIENTO: 'movement_number',
  CIDPRODUCTO: 'product_id',
  CIDALMACEN: 'warehouse_id',
  CUNIDADES: 'units',
  CUNIDADESCAPTURADAS: 'captured_units',
  CIDUNIDAD: 'unit_measure_id',
  CPRECIO: 'price',
  CPRECIOCAPTURADO: 'captured_price',
  CCOSTOCAPTURADO: 'captured_cost',
  CCOSTOESPECIFICO: 'specific_cost',
  CNETO: 'net_amount',
  CIMPUESTO1: 'tax_one',
  CIMPUESTO2: 'tax_two',
  CIMPUESTO3: 'tax_three',
  CRETENCION1: 'retention_one',
  CRETENCION2: 'retention_two',
  CDESCUENTO1: 'discount_one',
  CTOTAL: 'total',
  CREFERENCIA: 'reference',
  COBSERVAMOV: 'observations',
  CAFECTAEXISTENCIA: 'affects_stock',
  CFECHA: 'date',
  CIDVALORCLASIFICACION: 'classification',
  // En movimientos, CTEXTOEXTRA1 trae el eco de la unidad (R6 y
  // auto-link-movements de la app lo leen). Tampoco venía en el Action.
  CTEXTOEXTRA1: 'extra_text_one',
  CTEXTOEXTRA2: 'extra_text_two',
  CTEXTOEXTRA3: 'extra_text_three',
  CTIMESTAMP: 'sql_timestamp',
} as const;

/** admProductos → comercial_adm_products (30 columnas) */
export const PRODUCTOS_COLUMNS = {
  CIDPRODUCTO: 'product_id',
  CCODIGOPRODUCTO: 'product_code',
  CNOMBREPRODUCTO: 'product_name',
  CTIPOPRODUCTO: 'product_type',
  CSTATUSPRODUCTO: 'status',
  CFECHAALTAPRODUCTO: 'registration_date',
  CDESCRIPCIONPRODUCTO: 'description',
  CCLAVESAT: 'sat_key',
  CPRECIO1: 'price_one',
  CPRECIO2: 'price_two',
  CPRECIO3: 'price_three',
  CPRECIO4: 'price_four',
  CPRECIO5: 'price_five',
  CPRECIO6: 'price_six',
  CPRECIO7: 'price_seven',
  CPRECIO8: 'price_eight',
  CPRECIO9: 'price_nine',
  CPRECIO10: 'price_ten',
  CIMPUESTO1: 'tax_one',
  CIMPUESTO2: 'tax_two',
  CIMPUESTO3: 'tax_three',
  CIDVALORCLASIFICACION1: 'classification_one',
  CIDVALORCLASIFICACION2: 'classification_two',
  CIDVALORCLASIFICACION3: 'classification_three',
  CIDVALORCLASIFICACION4: 'classification_four',
  CIDVALORCLASIFICACION5: 'classification_five',
  CIDVALORCLASIFICACION6: 'classification_six',
  CMETODOCOSTEO: 'costing_method',
  CCONTROLEXISTENCIA: 'stock_control',
  CIDUNIDADBASE: 'base_unit_id',
} as const;

/** admConceptos → comercial_adm_concepts (199 columnas) */
export const CONCEPTOS_COLUMNS = {
  CIDCONCEPTODOCUMENTO: 'concept_id',
  CCODIGOCONCEPTO: 'concept_code',
  CNOMBRECONCEPTO: 'concept_name',
  CIDDOCUMENTODE: 'source_document_id',
  CNATURALEZA: 'nature',
  CDOCTOACREDITO: 'credit_document',
  CTIPOFOLIO: 'folio_type',
  CMAXIMOMOVTOS: 'max_movements',
  CCREACLIENTE: 'creates_client',
  CSUMARPROMOCIONES: 'add_promotions',
  CFORMAPREIMPRESA: 'preprinted_form',
  CORDENCALCULO: 'calculation_order',
  CUSANOMBRECTEPROV: 'uses_client_supplier_name',
  CUSARFC: 'uses_rfc',
  CUSAFECHAVENCIMIENTO: 'uses_due_date',
  CUSAFECHAENTREGARECEPCION: 'uses_delivery_reception_date',
  CUSAMONEDA: 'uses_currency',
  CUSATIPOCAMBIO: 'uses_exchange_rate',
  CUSACODIGOAGENTE: 'uses_agent_code',
  CUSANOMBREAGENTE: 'uses_agent_name',
  CUSADIRECCION: 'uses_address',
  CUSAREFERENCIA: 'uses_reference',
  CSERIEPOROMISION: 'default_series',
  CANCHOCODIGOPRODUCTO: 'product_code_width',
  CUSANOMBREPRODUCTO: 'uses_product_name',
  CANCHONOMBREPRODUCTO: 'product_name_width',
  CUSAALMACEN: 'uses_warehouse',
  CANCHOCODIGOALMACEN: 'warehouse_code_width',
  CANCHOIMPORTES: 'amounts_width',
  CANCHOPORCENTAJES: 'percentages_width',
  CANCHOUNIDADPESOMEDIDA: 'unit_weight_measure_width',
  CUSAPRECIO: 'uses_price',
  CIDFORMULAPRECIO: 'price_formula_id',
  CUSACOSTOCAPTURADO: 'uses_captured_cost',
  CIDFORMULACOSTOCAPTURADO: 'captured_cost_formula_id',
  CUSAEXISTENCIA: 'uses_stock',
  CUSANETO: 'uses_net',
  CIDFORMULANETO: 'net_formula_id',
  CUSAPORCENTAJEIMPUESTO1: 'uses_tax_percentage_one',
  CIDFORMULAPORCIMPUESTO1: 'tax_percentage_one_formula_id',
  CUSAIMPUESTO1: 'uses_tax_one',
  CIDFORMULAIMPUESTO1: 'tax_one_formula_id',
  CUSAPORCENTAJEIMPUESTO2: 'uses_tax_percentage_two',
  CIDFORMULAPORCIMPUESTO2: 'tax_percentage_two_formula_id',
  CUSAIMPUESTO2: 'uses_tax_two',
  CIDFORMULAIMPUESTO2: 'tax_two_formula_id',
  CUSAPORCENTAJEIMPUESTO3: 'uses_tax_percentage_three',
  CIDFORMULAPORCIMPUESTO3: 'tax_percentage_three_formula_id',
  CUSAIMPUESTO3: 'uses_tax_three',
  CIDFORMULAIMPUESTO3: 'tax_three_formula_id',
  CUSAPORCENTAJERETENCION1: 'uses_retention_percentage_one',
  CIDFORMULAPORCRETENCION1: 'retention_percentage_one_formula_id',
  CUSARETENCION1: 'uses_retention_one',
  CIDFORMULARETENCION1: 'retention_one_formula_id',
  CUSAPORCENTAJERETENCION2: 'uses_retention_percentage_two',
  CIDFORMULAPORCRETENCION2: 'retention_percentage_two_formula_id',
  CUSARETENCION2: 'uses_retention_two',
  CIDFORMULARETENCION2: 'retention_two_formula_id',
  CUSAPORCENTAJEDESCUENTO1: 'uses_discount_percentage_one',
  CIDFORMULAPORCDESCUENTO1: 'discount_percentage_one_formula_id',
  CUSADESCUENTO1: 'uses_discount_one',
  CIDFORMULADESCUENTO1: 'discount_one_formula_id',
  CUSAPORCENTAJEDESCUENTO2: 'uses_discount_percentage_two',
  CIDFORMULAPORCDESCUENTO2: 'discount_percentage_two_formula_id',
  CUSADESCUENTO2: 'uses_discount_two',
  CIDFORMULADESCUENTO2: 'discount_two_formula_id',
  CUSAPORCENTAJEDESCUENTO3: 'uses_discount_percentage_three',
  CIDFORMULAPORCDESCUENTO3: 'discount_percentage_three_formula_id',
  CUSADESCUENTO3: 'uses_discount_three',
  CIDFORMULADESCUENTO3: 'discount_three_formula_id',
  CUSAPORCENTAJEDESCUENTO4: 'uses_discount_percentage_four',
  CIDFORMULAPORCDESCUENTO4: 'discount_percentage_four_formula_id',
  CUSADESCUENTO4: 'uses_discount_four',
  CIDFORMULADESCUENTO4: 'discount_four_formula_id',
  CUSAPORCENTAJEDESCUENTO5: 'uses_discount_percentage_five',
  CIDFORMULAPORCDESCUENTO5: 'discount_percentage_five_formula_id',
  CUSADESCUENTO5: 'uses_discount_five',
  CIDFORMULADESCUENTO5: 'discount_five_formula_id',
  CUSATOTAL: 'uses_total',
  CANCHOREFERENCIA: 'reference_width',
  CUSACLASIFICACIONMOVTO: 'uses_movement_classification',
  CANCHOVALORCLASIFICACION: 'classification_value_width',
  CIDFORMULATOTAL: 'total_formula_id',
  CUSADESCUENTODOC1: 'uses_document_discount_one',
  CIDFORMULADESDOC1: 'document_discount_one_formula_id',
  CUSADESCUENTODOC2: 'uses_document_discount_two',
  CIDFORMULADESDOC2: 'document_discount_two_formula_id',
  CUSAGASTO1: 'uses_expense_one',
  CIDFORMULAGASTO1: 'expense_one_formula_id',
  CUSAGASTO2: 'uses_expense_two',
  CIDFORMULAGASTO2: 'expense_two_formula_id',
  CUSAGASTO3: 'uses_expense_three',
  CIDFORMULAGASTO3: 'expense_three_formula_id',
  CUSATEXTOEXTRA1: 'uses_extra_text_one',
  CUSATEXTOEXTRA2: 'uses_extra_text_two',
  CUSATEXTOEXTRA3: 'uses_extra_text_three',
  CANCHOTEXTOEXTRA: 'extra_text_width',
  CUSAFECHAEXTRA: 'uses_extra_date',
  CANCHOFECHAEXTRA: 'extra_date_width',
  CUSAIMPORTEEXTRA1: 'uses_extra_amount_one',
  CIDFORMULAEXTRA1: 'extra_one_formula_id',
  CUSAIMPORTEEXTRA2: 'uses_extra_amount_two',
  CIDFORMULAEXTRA2: 'extra_two_formula_id',
  CUSAIMPORTEEXTRA3: 'uses_extra_amount_three',
  CIDFORMULAEXTRA3: 'extra_three_formula_id',
  CUSAIMPORTEEXTRA4: 'uses_extra_amount_four',
  CIDFORMULAEXTRA4: 'extra_four_formula_id',
  CUSATEXTOEXTRA1DOC: 'uses_extra_text_one_doc',
  CUSATEXTOEXTRA2DOC: 'uses_extra_text_two_doc',
  CUSATEXTOEXTRA3DOC: 'uses_extra_text_three_doc',
  CUSAFECHAEXTRADOC: 'uses_extra_date_doc',
  CUSAIMPORTEEXTRA1DOC: 'uses_extra_amount_one_doc',
  CUSAIMPORTEEXTRA2DOC: 'uses_extra_amount_two_doc',
  CUSAIMPORTEEXTRA3DOC: 'uses_extra_amount_three_doc',
  CUSAIMPORTEEXTRA4DOC: 'uses_extra_amount_four_doc',
  CUSAEXTRACOMOGASTO: 'uses_extra_as_expense',
  CUSAOBSERVACIONES: 'uses_observations',
  CPRESENTAFISCAL: 'shows_fiscal',
  CPRESENTAREFERENCIA: 'shows_reference',
  CPRESENTACONDICIONES: 'shows_conditions',
  CPRESENTAENVIO: 'shows_shipping',
  CPRESENTADETALLE: 'shows_detail',
  CPRESENTAIMPRIMIR: 'shows_print',
  CPRESENTAPAGAR: 'shows_pay',
  CPRESENTASALDAR: 'shows_settle',
  CPRESENTADOCUMENTAR: 'shows_document',
  CPRESENTAGASTOSCOMPRA: 'shows_purchase_expenses',
  CSEGCONTCONCEPTO: 'concept_accounting_segment',
  CBANENCABEZADO: 'flag_header',
  CBANMOVIMIENTO: 'flag_movement',
  CBANDESCUENTO: 'flag_discount',
  CBANIMPUESTO: 'flag_tax',
  CBANACCIONAUTOMATICA: 'flag_automatic_action',
  CTIMESTAMP: 'sql_timestamp',
  CNOFOLIO: 'folio_number',
  CIDPROCESOSEGURIDAD: 'security_process_id',
  CUSAGTOMOV: 'uses_movement_expense',
  CUSASCMOV: 'uses_movement_accounting_segment',
  CIDASTOCON: 'automatic_accounting_id',
  CSCCPTO2: 'accounting_segment_two',
  CSCCPTO3: 'accounting_segment_three',
  CSCMOVTO: 'movement_accounting_segment',
  CIDCONAUTO: 'automatic_concept_id',
  CIDALMASUM: 'summary_warehouse_id',
  CUSACOMVTA: 'uses_sales_commission',
  CIDPRSEG02: 'security_process_two_id',
  CIDPRSEG03: 'security_process_three_id',
  CIDPRSEG04: 'security_process_four_id',
  CIDPRSEG05: 'security_process_five_id',
  CFORMAAJ01: 'adjustment_form',
  CIDPRSEG06: 'security_process_six_id',
  CAPFORMULA: 'apply_formula',
  CESCFD: 'is_cfd',
  CIDFIRMARL: 'signature_id',
  CGDAPASSW: 'password_protected',
  CEMITEYENT: 'emits_and_delivers',
  CBANCFD: 'flag_cfd',
  CREPIMPCFD: 'cfd_print_report',
  CIDDIRSUCU: 'branch_address_id',
  CBANDIRSUC: 'flag_branch_address',
  CVERFACELE: 'verify_electronic_invoice',
  CCALFECHAS: 'calculate_dates',
  CTIPCAMTR1: 'exchange_rate_type_one',
  CTIPCAMTR2: 'exchange_rate_type_two',
  CCONSOLIDA: 'consolidates',
  CENVIODIG: 'digital_delivery',
  CBANTRANS: 'flag_transfer',
  CCONFNOAPR: 'config_no_approval',
  CNOAPROB: 'no_approval',
  CAUTOIMPR: 'auto_print',
  CRECIBECFD: 'receives_cfd',
  CSISTORIG: 'source_system',
  CIDCPTODE1: 'concept_document_one_id',
  CIDCPTODE2: 'concept_document_two_id',
  CIDCPTODE3: 'concept_document_three_id',
  CPLAMIGCFD: 'cfd_migration_template',
  CIDPRSEG07: 'security_process_seven_id',
  CRESERVADO: 'reserved',
  CVERREFER: 'verify_reference',
  CVERDOCORI: 'verify_source_document',
  CCBB: 'cbb',
  CCARTAPOR: 'letter_of_credit',
  CCOMPDONAT: 'donation_receipt',
  COBSXML: 'xml_observations',
  CRUTAENTREGA: 'delivery_route',
  CPREFIJOCONCEPTO: 'concept_prefix',
  CREGIMFISC: 'fiscal_regime',
  CCOMPEDUCA: 'education_receipt',
  CMETODOPAG: 'payment_method',
  CVERESQUE: 'verify_scheme',
  CIDFIRMADSL: 'dsl_signature_id',
  CORDENCAPTURA: 'capture_order',
  CESTATUS: 'status',
  CIDMONEDA: 'currency_id',
  CIDCUENTA: 'account_id',
  CCLAVESAT: 'sat_key',
  CIDPRSEG08: 'security_process_eight_id',
  CUSAOBJIMP: 'uses_tax_object',
  CCONFIEPS: 'ieps_config',
} as const;

/** admExistenciaCosto → comercial_adm_stock_costs (59 columnas) */
export const EXISTENCIACOSTO_COLUMNS = {
  CIDEXISTENCIA: 'stock_id',
  CIDALMACEN: 'warehouse_id',
  CIDPRODUCTO: 'product_id',
  CIDEJERCICIO: 'fiscal_year_id',
  CTIPOEXISTENCIA: 'stock_type',
  CENTRADASINICIALES: 'initial_entries',
  CSALIDASINICIALES: 'initial_exits',
  CCOSTOINICIALENTRADAS: 'initial_entries_cost',
  CCOSTOINICIALSALIDAS: 'initial_exits_cost',
  CENTRADASPERIODO1: 'entries_period_1',
  CENTRADASPERIODO2: 'entries_period_2',
  CENTRADASPERIODO3: 'entries_period_3',
  CENTRADASPERIODO4: 'entries_period_4',
  CENTRADASPERIODO5: 'entries_period_5',
  CENTRADASPERIODO6: 'entries_period_6',
  CENTRADASPERIODO7: 'entries_period_7',
  CENTRADASPERIODO8: 'entries_period_8',
  CENTRADASPERIODO9: 'entries_period_9',
  CENTRADASPERIODO10: 'entries_period_10',
  CENTRADASPERIODO11: 'entries_period_11',
  CENTRADASPERIODO12: 'entries_period_12',
  CSALIDASPERIODO1: 'exits_period_1',
  CSALIDASPERIODO2: 'exits_period_2',
  CSALIDASPERIODO3: 'exits_period_3',
  CSALIDASPERIODO4: 'exits_period_4',
  CSALIDASPERIODO5: 'exits_period_5',
  CSALIDASPERIODO6: 'exits_period_6',
  CSALIDASPERIODO7: 'exits_period_7',
  CSALIDASPERIODO8: 'exits_period_8',
  CSALIDASPERIODO9: 'exits_period_9',
  CSALIDASPERIODO10: 'exits_period_10',
  CSALIDASPERIODO11: 'exits_period_11',
  CSALIDASPERIODO12: 'exits_period_12',
  CCOSTOENTRADASPERIODO1: 'entries_cost_period_1',
  CCOSTOENTRADASPERIODO2: 'entries_cost_period_2',
  CCOSTOENTRADASPERIODO3: 'entries_cost_period_3',
  CCOSTOENTRADASPERIODO4: 'entries_cost_period_4',
  CCOSTOENTRADASPERIODO5: 'entries_cost_period_5',
  CCOSTOENTRADASPERIODO6: 'entries_cost_period_6',
  CCOSTOENTRADASPERIODO7: 'entries_cost_period_7',
  CCOSTOENTRADASPERIODO8: 'entries_cost_period_8',
  CCOSTOENTRADASPERIODO9: 'entries_cost_period_9',
  CCOSTOENTRADASPERIODO10: 'entries_cost_period_10',
  CCOSTOENTRADASPERIODO11: 'entries_cost_period_11',
  CCOSTOENTRADASPERIODO12: 'entries_cost_period_12',
  CCOSTOSALIDASPERIODO1: 'exits_cost_period_1',
  CCOSTOSALIDASPERIODO2: 'exits_cost_period_2',
  CCOSTOSALIDASPERIODO3: 'exits_cost_period_3',
  CCOSTOSALIDASPERIODO4: 'exits_cost_period_4',
  CCOSTOSALIDASPERIODO5: 'exits_cost_period_5',
  CCOSTOSALIDASPERIODO6: 'exits_cost_period_6',
  CCOSTOSALIDASPERIODO7: 'exits_cost_period_7',
  CCOSTOSALIDASPERIODO8: 'exits_cost_period_8',
  CCOSTOSALIDASPERIODO9: 'exits_cost_period_9',
  CCOSTOSALIDASPERIODO10: 'exits_cost_period_10',
  CCOSTOSALIDASPERIODO11: 'exits_cost_period_11',
  CCOSTOSALIDASPERIODO12: 'exits_cost_period_12',
  CBANCONGELADO: 'frozen',
  CTIMESTAMP: 'sql_timestamp',
} as const;

/** admFoliosDigitales → comercial_adm_digital_stamps (23 columnas) */
export const FOLIOSDIGITALES_COLUMNS = {
  CIDFOLDIG: 'digital_stamp_id',
  CIDDOCTODE: 'source_document_id',
  CIDCPTODOC: 'document_concept_id',
  CIDDOCTO: 'document_id',
  CSERIE: 'series',
  CFOLIO: 'folio',
  CNOAPROB: 'approval_number',
  CFECAPROB: 'approval_date',
  CESTADO: 'state',
  CENTREGADO: 'delivered',
  CFECHAEMI: 'emission_date',
  CHORAEMI: 'emission_time',
  CEMAIL: 'email',
  CFECHACANC: 'cancellation_date',
  CHORACANC: 'cancellation_time',
  CRFC: 'rfc',
  CRAZON: 'business_name',
  CTOTAL: 'total',
  CUUID: 'uuid',
  CCADPEDI: 'petition_chain',
  CTIPO: 'type',
  CDESESTADO: 'state_description',
  CACUSECAN: 'cancellation_receipt',
} as const;

/** admCostosHistoricos → comercial_adm_historical_costs (8 columnas) */
export const COSTOSHISTORICOS_COLUMNS = {
  CIDCOSTOH: 'historical_cost_id',
  CIDPRODUCTO: 'product_id',
  CIDALMACEN: 'warehouse_id',
  CFECHACOSTOH: 'cost_date',
  CCOSTOH: 'cost',
  CULTIMOCOSTOH: 'last_cost',
  CIDMOVIMIENTO: 'movement_id',
  CTIMESTAMP: 'sql_timestamp',
} as const;

/** admAlmacenes → comercial_adm_warehouses (5 columnas) */
export const ALMACENES_COLUMNS = {
  CIDALMACEN: 'warehouse_id',
  CCODIGOALMACEN: 'warehouse_code',
  CNOMBREALMACEN: 'warehouse_name',
  CFECHAALTAALMACEN: 'registration_date',
  CTIMESTAMP: 'sql_timestamp',
} as const;

/** admPreciosCompra → comercial_adm_purchase_prices (8 columnas) */
export const PRECIOSCOMPRA_COLUMNS = {
  CIDAUTOINCSQL: 'purchase_price_id',
  CIDPRODUCTO: 'product_id',
  CIDPROVEEDOR: 'supplier_id',
  CPRECIOCOMPRA: 'purchase_price',
  CIDMONEDA: 'currency_id',
  CCODIGOPRODUCTOPROVEEDOR: 'supplier_product_code',
  CIDUNIDAD: 'unit_measure_id',
  CTIMESTAMP: 'sql_timestamp',
} as const;
